### ISSUE TITLE
Implement event watchers for downstream subscribers

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/uniswap-watcher-ts#116]
for uni-watcher

- [x] Factory
- [x] Pool
- [x] Non Fungible Position Manager

**Comment by ashwinphatak** [comment]
Pool initialize throws an error, need to debug on local hardhat instance (with source):

```
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x272b0e2394e4664f0417a2de209e880d7123c196
  Value:               0 ETH

  Error: VM Exception while processing transaction: revert R
      at <UnrecognizedContract>.<unknown> (0x272b0e2394e4664f0417a2de209e880d7123c196)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthModule._estimateGasAction (/home/ashwinp/projects/ashwinp/watcher-ts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:421:9)
      at HardhatNetworkProvider._sendWithLogging (/home/ashwinp/projects/ashwinp/watcher-ts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:119:22)
      at HardhatNetworkProvider.request (/home/ashwinp/projects/ashwinp/watcher-ts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:99:18)

```
