### ISSUE TITLE
Replace storage slots reads with eth_calls

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/uniswap-watcher-ts#271]

**Comment by nikugogoi** [comment]
In docker implementation eth_call throws an error

Points checked:
* The configured url endpoint for ethersjs is correct and pointing to ipld-eth-server.
* There are no logs in ipld-eth-server i.e. the eth_calls are not made to ipld-eth-server.
* The eth_calls work after stopping docker-compose once and starting again.

```
uni-info-watcher-job-runner_1  | 2021-10-22T05:41:41.118Z vulcanize:job-runner Processing event 9
uni-info-watcher-job-runner_1  | 2021-10-22T05:41:41.129Z vulcanize:indexer NFPM Transfer event 0x24CFBe2986e09aB7B7A5E4f8a6bF629B81840ef1
uni-watcher-server_1           | 2021-10-22T05:41:41.172Z vulcanize:resolver positions 0xbbd8547f31ec389677ad746c4611e034c10cf910c0192c729b642b834960e368 0x24CFBe2986e09aB7B7A5E4f8a6bF629B81840ef1 1
uni-info-watcher-job-runner_1  | 2021-10-22T05:41:41.216Z vulcanize:indexer nfpm positions eth_call failed
uni-info-watcher-job-runner_1  | 2021-10-22T05:41:41.216Z vulcanize:job-queue Error in queue event-processing
uni-info-watcher-job-runner_1  | 2021-10-22T05:41:41.270Z vulcanize:job-queue /app/node_modules/@apollo/client/errors/index.js:26
uni-info-watcher-job-runner_1  |         var _this = _super.call(this, errorMessage) || this;
uni-info-watcher-job-runner_1  |                            ^
uni-info-watcher-job-runner_1  | 
uni-info-watcher-job-runner_1  | Error: underlying network changed (event="changed", network={"name":"unspecified","chainId":0,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.3.0)
uni-info-watcher-job-runner_1  |     at new ApolloError (/app/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/errors/index.js:26:28
uni-info-watcher-job-runner_1  |     at /app/node_modules/@apollo/client/core/core.cjs.js:1474:47
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/core/QueryManager.js:517:47
uni-info-watcher-job-runner_1  |     at both (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:963:53)
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53
uni-info-watcher-job-runner_1  |     at /app/node_modules/@apollo/client/utilities/utilities.cjs.js:956:72
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
uni-info-watcher-job-runner_1  |     at new Promise (<anonymous>)
uni-info-watcher-job-runner_1  |     at Object.then (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:956:24)
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24
uni-info-watcher-job-runner_1  |     at Object.next (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:964:49)
uni-info-watcher-job-runner_1  |         -> /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49
uni-info-watcher-job-runner_1  |     at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:135:18)
uni-info-watcher-job-runner_1  |     at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
uni-info-watcher-job-runner_1  |     at SubscriptionObserver.next (/app/node_modules/zen-observable/lib/Observable.js:235:7)
```
_NOTE_: Doesnt throw error after stopping and starting the docker-compose services again.

New issue created https://github.com/vulcanize/watcher-ts/issues/291
